### ISSUE TITLE
Good way to put Struct and Class in params object[] args?

### ISSUE THREAD

**Issue by nvh2001** [alec1o/Byter#26]
How can we identify Struct and Class in switch case as other primitive variables?
```
public void SendPacket(PacketTypeEnum type, params object[] args)
{
    packetStorage.Reset();
    packetStorage.Add.UShort((ushort)type);
    foreach (var arg in args)
    {
        switch (arg)
        {
            case bool boolValue:
                packetStorage.Add.Bool(boolValue);
                break;
            case byte byteValue:
                packetStorage.Add.Byte(byteValue);
                break;
            case sbyte sbyteValue:
                packetStorage.Add.SByte(sbyteValue);
                break;
            case char charValue:
                packetStorage.Add.Char(charValue);
                break;
            case short shortValue:
                packetStorage.Add.Short(shortValue);
                break;
            case ushort ushortValue:
                packetStorage.Add.UShort(ushortValue);
                break;
            case int intValue:
                packetStorage.Add.Int(intValue);
                break;
            case uint uintValue:
                packetStorage.Add.UInt(uintValue);
                break;
            case float floatValue:
                packetStorage.Add.Float(floatValue);
                break;
            case double doubleValue:
                packetStorage.Add.Double(doubleValue);
                break;
            case long longValue:
                packetStorage.Add.Long(longValue);
                break;
            case ulong ulongValue:
                packetStorage.Add.ULong(ulongValue);
                break;
            case decimal decimalValue:
                packetStorage.Add.Decimal(decimalValue);
                break;
            case DateTime dateTimeValue:
                packetStorage.Add.DateTime(dateTimeValue);
                break;
            case string stringValue:
                packetStorage.Add.String(stringValue);
                break;
            case BigInteger bigIntegerValue:
                packetStorage.Add.BigInteger(bigIntegerValue);
                break;
            case byte[] bytesValue:
                packetStorage.Add.Bytes(bytesValue);
                break;
            default:
                throw new ArgumentException($"Unsupported type: {arg.GetType()}");
        }
    }
   packetSender.AddPacket(packetStorage.GetBytes());
}
```

**Comment by alec1o** [comment]
Hey. You can use: typeof(T)
Consider using generic function parameter to be more easy (is very hard detect if a object is a class because typeof(object) is a class too).

**Comment by alec1o** [comment]
I recreate for you with same usage :blue_heart: (this code bellow have all supported primitive types)
Based on (Primitive Extension): [Byter/src/src/extension/PrimitiveExtension.cs](https://github.com/alec1o/Byter/blob/v3.0/src/src/extension/PrimitiveExtension.cs)


```cs
using System;
using System.Collections;
using System.Numerics;

public void SendPacket<T>(PacketTypeEnum type, params T[] values)
{
    primitive.Reset();
    primitive.Add.Enum(type);
    
    foreach (var value in values)
    {
        var xType = value.GetType();
        
        // 1 byte (3)
        if (value is bool)
        {
            packetStorage.Add.Bool((bool)blackbox);
        }
        else if (value is byte)
        {
            primitive.Add.Byte((byte)blackbox);
        }
        else if (value is sbyte)
        {
            primitive.Add.SByte((sbyte)blackbox);
        }
        // 2 bytes (3)
        else if (value is char)
        {
            primitive.Add.Char((char)blackbox);
        }
        else if (value is short)
        {
            primitive.Add.Short((short)blackbox);
        }
        else if (value is ushort)
        {
            primitive.Add.UShort((ushort)blackbox);
        }
        // 4 bytes (4)
        else if (value is int)
        {
            primitive.Add.Int((int)blackbox);
        }
        else if (value is uint)
        {
            primitive.Add.UInt((uint)blackbox);
        }
        else if (value is float)
        {
            primitive.Add.Float((float)blackbox);
        }
        else if (value is Enum || type.IsEnum)
        {
            primitive.Add.Enum(value);
        }
        // 8 bytes (3)
        else if (value is long)
        {
            primitive.Add.Long((long)blackbox);
        }
        else if (value is ulong)
        {
            primitive.Add.ULong((ulong)blackbox);
        }
        else if (value is double)
        {
            primitive.Add.Double((double)blackbox);
        }
        else if (value is DateTime)
        {
            primitive.Add.DateTime((DateTime)blackbox);
        }
        // 16 bytes (1)
        else if (value is decimal)
        {
            primitive.Add.Decimal((decimal)blackbox);
        }
        // dynamic (7)
        else if (value is string)
        {
            primitive.Add.String((string)blackbox);
        }
        else if (value is BigInteger)
        {
            primitive.Add.BigInteger((BigInteger)blackbox);
        }
        else if (value is byte[])
        {
            primitive.Add.Bytes((byte[])blackbox);
        }
        else if (type.IsArray || value is T[])
        {
            primitive.Add.Array(value);
        }
        else if (value is ICollection)
        {
            primitive.Add.List(value);
        }
        else if (xType.IsValueType && !xType.IsEnum && !xType.IsPrimitive)
        {
            primitive.Add.Struct(value);
        }
        else if (xType.IsClass)
        {
            primitive.Add.Class(value);
        }
        else
        {
            throw new NotImplementedException($"typeof({value}) is not implemented");
        }
    }

    packetSender.AddPacket(primitive.GetBytes());
}
```

**Comment by nvh2001** [comment]
> I recreated (SendPacket) for you, with same usage 💙 (this code bellow have all supported primitive types) Based on (Primitive Extension): [Byter/src/src/extension/PrimitiveExtension.cs](https://github.com/alec1o/Byter/blob/v3.0/src/src/extension/PrimitiveExtension.cs)
> 
> ```cs
> using System;
> using System.Collections;
> using System.Numerics;
> 
> public void SendPacket<T>(PacketTypeEnum type, params T[] values)
> {
>     primitive.Reset();
>     primitive.Add.Enum(type);
>     
>     foreach (T value in values)
>     {
>         object blackbox = value;
>         var xType = value.GetType();
>         
>         // 1 byte (3)
>         if (value is bool)
>         {
>             packetStorage.Add.Bool((bool)blackbox);
>         }
>         else if (value is byte)
>         {
>             primitive.Add.Byte((byte)blackbox);
>         }
>         else if (value is sbyte)
>         {
>             primitive.Add.SByte((sbyte)blackbox);
>         }
>         // 2 bytes (3)
>         else if (value is char)
>         {
>             primitive.Add.Char((char)blackbox);
>         }
>         else if (value is short)
>         {
>             primitive.Add.Short((short)blackbox);
>         }
>         else if (value is ushort)
>         {
>             primitive.Add.UShort((ushort)blackbox);
>         }
>         // 4 bytes (4)
>         else if (value is int)
>         {
>             primitive.Add.Int((int)blackbox);
>         }
>         else if (value is uint)
>         {
>             primitive.Add.UInt((uint)blackbox);
>         }
>         else if (value is float)
>         {
>             primitive.Add.Float((float)blackbox);
>         }
>         else if (value is Enum || type.IsEnum)
>         {
>             primitive.Add.Enum(value);
>         }
>         // 8 bytes (3)
>         else if (value is long)
>         {
>             primitive.Add.Long((long)blackbox);
>         }
>         else if (value is ulong)
>         {
>             primitive.Add.ULong((ulong)blackbox);
>         }
>         else if (value is double)
>         {
>             primitive.Add.Double((double)blackbox);
>         }
>         else if (value is DateTime)
>         {
>             primitive.Add.DateTime((DateTime)blackbox);
>         }
>         // 16 bytes (1)
>         else if (value is decimal)
>         {
>             primitive.Add.Decimal((decimal)blackbox);
>         }
>         // dynamic (7)
>         else if (value is string)
>         {
>             primitive.Add.String((string)blackbox);
>         }
>         else if (value is BigInteger)
>         {
>             primitive.Add.BigInteger((BigInteger)blackbox);
>         }
>         else if (value is byte[])
>         {
>             primitive.Add.Bytes((byte[])blackbox);
>         }
>         else if (type.IsArray || value is T[])
>         {
>             primitive.Add.Array(value);
>         }
>         else if (value is ICollection)
>         {
>             primitive.Add.List(value);
>         }
>         else if (xType.IsValueType && !xType.IsEnum && !xType.IsPrimitive)
>         {
>             primitive.Add.Struct(value);
>         }
>         else if (xType.IsClass)
>         {
>             primitive.Add.Class(value);
>         }
>         else
>         {
>             throw new NotImplementedException($"typeof({value}) is not implemented");
>         }
>     }
> 
>     packetSender.AddPacket(primitive.GetBytes());
> }
> ```

awesome, tks u

**Comment by alec1o** [comment]
I feel happy to help you. 💎
Aways contact me if you have any questions or problems. 🏆
I hope you have a great day and great progress in developing your MMORPG. 🥳
